name: Node.js CI

on:
  push:
    branches:
      - master
      - github-action-test
  pull_request:
    branches:
      - master
      - github-action-test

env:
    CI: true
    TZ: "America/Chicago"
    API_URL: "https://api-test.speechanddebate.org/v2/"
    API_HOST: "api-test.speechanddebate.org"
    test: "false"
    cache-name: "node-modules"
    Succeeded: ":heavy_check_mark: Succeeded"
    Failed: ":heavy_multiplication_x: Failed"
    testValue: "test value"
    SLACK_ICON: ":octocat:"
    SLACK_CHANNEL: "#test-channel"
    SLACK_USERNAME: "Github Actions"
    SLACK_COLOR: "#de4e2b"
    SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    SLACK_TITLE: ":heavy_multiplication_x: Failed"

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - name: test
      run: |
        echo "::set-env name=test::true"
        echo "::set-env name=testValue::${{ env.Succeeded }}"

    - name: printenv
      run: printenv

    - name: test true
      if: env.test == 'true'
      run: echo "got here (true)"

    - name: test false
      if: env.test == false
      run: echo "got here (false)"

    - name: Slack Notification
      uses: PaulSearcy/action-status-slack@0.5
      env:
        SLACK_MESSAGE: 'Post Content test'
